<Album>
    orientation:'vertical'

    GridLayout:
        orientation: "vertical"
        size: 100, 100

        padding: 20
        spacing: 20

            Image:
                fit_mode = "cover"

<Group>
    orientation:'vertical'

    GridLayout:
        orientation: "vertical"
        size: 100, 100

        padding: 20
        spacing: 20

            Image:
                source: {later}
